name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        # Remove the cache parameter or set it to 'maven' instead of 'gradle'
        # cache: gradle
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        # Configure custom cache keys
        gradle-home-cache-cleanup: true
      
    - name: Build with Gradle
      run: gradle build --warning-mode all || true
      
    - name: Build Debug APK
      run: gradle assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
